- name: Install mise and initialize configuration
  hosts: localhost
  tasks:
    - name: Install mise
      homebrew:
        name: mise
        state: present
    - name: Create config dir
      file:
        path: "~/.config/mise"
        state: directory
        mode: 0755
    - name: Initialize config
      copy:
        src: "./config.toml"
        dest: "~/.config/mise/config.toml"
    - name: Install tools
      shell: "mise install"
    - name: Check if activate mise globally
      shell: 'cat ~/.zshrc | grep ''eval "$(mise activate zsh)"'''
      register: mise_state
      ignore_errors: yes
    - name: Activate globally
      shell: 'echo ''eval "$(mise activate zsh)"'' >> ~/.zshrc'
      when: mise_state is failed
